name: Check Spelling

on:
  pull_request_target:
    branches:
    - '**'
    types:
    - opened
    - reopened
    - synchronize

  push:
    paths:
    - '**/*.mdx'

jobs:
  spelling:
    name: Check Spelling
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run spell check
      uses: check-spelling/check-spelling@v0.0.22
      with:
        suppress_push_for_open_pull_request: 1
        check_file_names: 1
        spell_check_this: check-spelling/spell-check-this@prerelease
        use_sarif: 0
        experimental_apply_changes_via_bot: 0
        post_comment: 1
        extra_dictionaries:
          cspell:software-terms/dict/softwareTerms.txt
          cspell:php/dict/php.txt
          cspell:node/node.txt
          cspell:python/src/python/python-lib.txt
        ignore-pattern: '[^\p{Ll}\p{Lm}\p{Lt}\p{Lu}]'
        upper-pattern: '[\p{Lu}\p{Lt}\p{Lm}]'
        lower-pattern: '[\p{Ll}\p{Lm}]'
        not-lower-pattern: '[^\p{Ll}\p{Lm}]'
        not-upper-or-lower-pattern: '[^\p{Lu}\p{Lt}\p{Lm}]'
        punctuation-pattern: "'"
        exclusions: |
          asi
          FetchAI
