name: Check Spelling

on:
  push:
    branches:
      - "**"
    paths:
      - "docs/**/*.mdx"  # Scan only .mdx files in the docs directory and subdirectories
  pull_request_target:
    branches:
      - "**"
    types:
      - 'opened'
      - 'reopened'
      - 'synchronize'
    paths:
      - "docs/**/*.mdx"  # Scan only .mdx files in the docs directory and subdirectories

jobs:
  spell-check:
    name: Check Spelling
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install check-spelling
        run: pip install check-spelling

      - name: Run spell check
        id: spelling
        run: |
          check-spelling --config .github/actions/spelling/spelling.yml

      - name: Upload spellcheck logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: spellcheck-logs
          path: artifacts/

  comment-pr:
    name: Report (PR)
    runs-on: ubuntu-latest
    needs: spell-check
    permissions:
      contents: write
      pull-requests: write
    if: failure() && github.event_name == 'pull_request'
    steps:
      - name: Comment on PR
        uses: check-spelling/check-spelling@main
        with:
          spell_check_this: check-spelling/spell-check-this@prerelease
          task: ${{ needs.spell-check.outputs.followup }}
          experimental_apply_changes_via_bot: 1
