name: Spell Check Documentation

# Trigger the workflow on pull request only
on:
  pull_request:
    paths:
      - 'docs/**/*.mdx'  # Scan only .mdx files in the docs directory

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Spell Check Action
      uses: check-spelling/check-spelling@main
      with:
        config: .github/actions/spelling/spelling.yml  # Reference the config file

    - name: Upload spellcheck logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: spellcheck-logs
        path: artifacts/
