name: Check Spelling

on:
  push:
    branches:
      - "**"
  pull_request_target:
    branches:
      - "**"
    types:
      - 'opened'
      - 'reopened'
      - 'synchronize'

jobs:
  spelling:
    name: Check Spelling
    permissions:
      contents: read
      pull-requests: read
      actions: read
      security-events: write  # Optional for Sarif report generation (see commented section)
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || contains(github.event_name, 'pull_request') }}
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Spelling
        id: spelling
        uses: check-spelling/spell-check-this@main
        with:
          # Options to customize the spell checking process
          # Refer to https://github.com/check-spelling/spell-check-this/blob/main/.github/actions/spelling/README.md for details
          # Some examples:
          #   check_file_names: 1  # Check filenames for typos
          #   post_comment: 0  # Disable automatic comment posting
          #   use_magic_file: 1  # Use magic file for file type detection
          #   report-timing: 1  # Report execution time of each step
          #   warnings: bad-regex,...  # Specify warnings to identify (comma separated list)

# Optional jobs for automatic comment reporting (requires configuration)
# Comment out these sections if not desired

#      comment-push:
#        name: Report (Push)
#        runs-on: ubuntu-latest
#        needs: spelling
#        permissions:
#          contents: write
#        if: (success() || failure()) && needs.spelling.outputs.followup && github.event_name == 'push'
#        steps:
#          - name: comment
#            uses: check-spelling/spell-check-this@main
#            with:
#              checkout: true
#              task: ${{ needs.spelling.outputs.followup }}

#      comment-pr:
#        name: Report (PR)
#        runs-on: ubuntu-latest
#        needs: spelling
#        permissions:
#          contents: read
#          pull_requests: write
#        if: (success() || failure()) && needs.spelling.outputs.followup && contains(github.event_name, 'pull_request')
#        steps:
#          - name: comment
#            uses: check-spelling/spell-check-this@main
#            with:
#              checkout: true
#              task: ${{ needs.spelling.outputs.followup }}